### ISSUE TITLE
Timeout crashing container

### ISSUE THREAD

**Issue by bmutari** [zaknye/xcel_itron2mqtt#22]
Thank you for this! I'm in Denver too and just found out about how to tap into our new smart meters!

The container is successfully running for varying amounts of time but seems to stop with the logs showing a HTTP request timeout error.

I have tried both using the METER_IP and METER_PORT variables and letting is use mDNS, both have the same timeout problem.

I am running a Ubiquiti system and don't see any wifi disconnects from the meter. I have also reserved the meter IP. 

This what the log is showing: 

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.10/http/client.py", line 1375, in getresponse
    response.begin()
  File "/usr/local/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.10/http/client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.10/socket.py", line 705, in readinto
    return self._sock.recv_into(b)
  File "/usr/local/lib/python3.10/ssl.py", line 1307, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/local/lib/python3.10/ssl.py", line 1163, in read
    return self._sslobj.read(len, buffer)
TimeoutError: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.10/site-packages/urllib3/packages/six.py", line 770, in reraise
    raise value
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 451, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 340, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='10.25.83.66', port=8081): Read timed out. (read timeout=4.0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/xcel_itron2mqtt/main.py", line 81, in <module>
    meter.run()
  File "/opt/xcel_itron2mqtt/xcelMeter.py", line 229, in run
    obj.run()
  File "/opt/xcel_itron2mqtt/xcelEndpoint.py", line 172, in run
    reading = self.get_reading()
  File "/opt/xcel_itron2mqtt/xcelEndpoint.py", line 79, in get_reading
    response = self.query_endpoint()
  File "/opt/xcel_itron2mqtt/xcelEndpoint.py", line 42, in query_endpoint
    x = self.requests_session.get(self.url, verify=False, timeout=4.0)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 578, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='10.25.83.66', port=8081): Read timed out. (read timeout=4.0)
Connected to MQTT Broker!
```

**Comment by iubmadiwtu** [comment]
The docker should be set to restart always 
...
--restart always 
...
it's losing the connection with the unit, not something wrong with the software as soon as it gets back on the wifi it will get the next reading.  there's an issue tracking it with excel https://github.com/Xcel-Energy/energy-launchpadsdk-client/issues/6

**Comment by bmutari** [comment]
Thanks, I set it to --restart unless-stopped. It's working now, container is restarting at various intervals when it hits the timeout. 

Thanks for that link to the Xcel launchpad issue tracking, looks like the community is well onto the issue. 

Appreciate the help.

**Comment by zaknye** [comment]
Yup! Looks like @iubmadiwtu exposed the hack we're using for renewing broken connections.

In the future I need to rework it to work more like a state machine that will revert back to negotiating a connection when a connection is lost rather than leaning on Docker's restart behavior to pick up the slack.

**Comment by seevee** [comment]
Similar story here, Ubiquiti networking gear, no visible disconnects, exact same traceback. I'm using this project by way of [wingrunr21/hassio-xcel-itron-mqtt](https://github.com/wingrunr21/hassio-xcel-itron-mqtt).

Yesterday I was able to get it working again by restarting the service, but today it's been throwing this error on each attempted restart.

**Comment by kkellner** [comment]
I'm seeing the same thing, in Denver and use Ubiquiti.   Timeouts frequently.   I wonder if we make the timeout configurable on the connections (looks like its hard coded to 4 seconds).   This may help the issue where wifi may be iffy.

**Comment by doubleangels** [comment]
I'm also seeing the same issues, but a different traceback. I'm using Ubiquiti, and there are no visible disconnects from my network. Traceback is as follows:

` ✔ Container itron2mqtt  Created                                                                                                                                          0.1s 
Attaching to itron2mqtt
itron2mqtt  | Traceback (most recent call last):
itron2mqtt  |   File "/opt/xcel_itron2mqtt/main.py", line 63, in mDNS_search_for_meter
itron2mqtt  |     addresses = listener.info.addresses
itron2mqtt  | AttributeError: 'NoneType' object has no attribute 'addresses'
itron2mqtt  | 
itron2mqtt  | During handling of the above exception, another exception occurred:
itron2mqtt  | 
itron2mqtt  | Traceback (most recent call last):
itron2mqtt  |   File "/opt/xcel_itron2mqtt/main.py", line 81, in <module>
itron2mqtt  |     ip_address, port_num = mDNS_search_for_meter()
itron2mqtt  |   File "/opt/xcel_itron2mqtt/main.py", line 65, in mDNS_search_for_meter
itron2mqtt  |     raise TimeoutError('Waiting too long to get response from meter')
itron2mqtt  | TimeoutError: Waiting too long to get response from meter
itron2mqtt exited with code 1`

This seems to occur both when I allow the container to use mDNS or specify the METER_IP_ADDRESS.

**Comment by zaknye** [comment]
@doubleangels You will need to specify both `METER_IP` and `METER_PORT`. The error your receiving will only happen when an mDNS search fails to find the meter.

**Comment by doubleangels** [comment]
@zaknye Thanks! I'll give this a shot.
